In [ ]:
get_ipython().ast_node_interactivity = 'all'
import pandas 
import numpy
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn.metrics
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import FeatureUnion
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree

from sklearn.ensemble import BaggingClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import GridSearchCV

from sklearn.neural_network import MLPClassifier 

## Load data, split, make preprocessor

In [20]:
cd

C:\Users\Mika Montonen


C:\Users\Mika Montonen\miniconda3\lib\site-packages\IPython\core\magics\osm.py:393: UserWarning: using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})
C:\Users\Mika Montonen\miniconda3\lib\site-packages\IPython\core\magics\osm.py:428: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [21]:
%cd Downloads

C:\Users\Mika Montonen\Downloads


C:\Users\Mika Montonen\miniconda3\lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [22]:
%cd MLAi

C:\Users\Mika Montonen\Downloads\MLAi


In [23]:
df= pandas.read_csv( "creditCardDefault.csv" )
df.describe()

Limit_Bal     Education           Age         Pay_0         Pay_2  \
count    30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean    167484.322667      1.853133     35.485500     -0.016700     -0.133767   
std     129747.661567      0.790349      9.217904      1.123802      1.197186   
min      10000.000000      0.000000     21.000000     -2.000000     -2.000000   
25%      50000.000000      1.000000     28.000000     -1.000000     -1.000000   
50%     140000.000000      2.000000     34.000000      0.000000      0.000000   
75%     240000.000000      2.000000     41.000000      0.000000      0.000000   
max    1000000.000000      6.000000     79.000000      8.000000      8.000000   

              Pay_3         Pay_4         Pay_5         Pay_6      Bill_Amt1  \
count  30000.000000  30000.000000  30000.000000  30000.000000   30000.000000   
mean      -0.166200     -0.220667     -0.266200     -0.291100   51223.330900   
std        1.196868      1.169139      1.133187      1.149988   73635.860576   
min       -2.000000     -2.000000     -2.000000     -2.000000 -165580.000000   
25%       -1.000000     -1.000000     -1.000000     -1.000000    3558.750000   
50%        0.000000      0.000000      0.000000      0.000000   22381.500000   
75%        0.000000      0.000000      0.000000      0.000000   67091.000000   
max        8.000000      8.000000      8.000000      8.000000  964511.000000   

       ...     Bill_Amt3      Bill_Amt4      Bill_Amt5      Bill_Amt6  \
count  ...  3.000000e+04   30000.000000   30000.000000   30000.000000   
mean   ...  4.701315e+04   43262.948967   40311.400967   38871.760400   
std    ...  6.934939e+04   64332.856134   60797.155770   59554.107537   
min    ... -1.572640e+05 -170000.000000  -81334.000000 -339603.000000   
25%    ...  2.666250e+03    2326.750000    1763.000000    1256.000000   
50%    ...  2.008850e+04   19052.000000   18104.500000   17071.000000   
75%    ...  6.016475e+04   54506.000000   50190.500000   49198.250000   
max    ...  1.664089e+06  891586.000000  927171.000000  961664.000000   

            Pay_Amt1      Pay_Amt2      Pay_Amt3       Pay_Amt4  \
count   30000.000000  3.000000e+04   30000.00000   30000.000000   
mean     5663.580500  5.921163e+03    5225.68150    4826.076867   
std     16563.280354  2.304087e+04   17606.96147   15666.159744   
min         0.000000  0.000000e+00       0.00000       0.000000   
25%      1000.000000  8.330000e+02     390.00000     296.000000   
50%      2100.000000  2.009000e+03    1800.00000    1500.000000   
75%      5006.000000  5.000000e+03    4505.00000    4013.250000   
max    873552.000000  1.684259e+06  896040.00000  621000.000000   

            Pay_Amt5       Pay_Amt6  
count   30000.000000   30000.000000  
mean     4799.387633    5215.502567  
std     15278.305679   17777.465775  
min         0.000000       0.000000  
25%       252.500000     117.750000  
50%      1500.000000    1500.000000  
75%      4031.500000    4000.000000  
max    426529.000000  528666.000000  

[8 rows x 21 columns]

#### Construct your first neural network

In [33]:
numpy.random.seed(28)
X_train, X_test, y_train, y_test = train_test_split( df, df.Payment, test_size=0.5)

In [34]:
lstNum = ['Limit_Bal','Age','Bill_Amt1','Pay_Amt1']
lstCat = ['Card', 'Marriage','Pay_0']

pipeNum = Pipeline( [
    ('selector', ColumnTransformer([ ('selector', 'passthrough', lstNum ) ] )),
    ('scaler', StandardScaler() )
])
pipeCat = Pipeline([
    ('selector', ColumnTransformer([ ('selector', 'passthrough', lstCat ) ] )),
    ('encoder', OneHotEncoder( dtype=int, drop='first', sparse_output=False ) )
])

preprocessor = FeatureUnion([ ('cat', pipeCat ), ('num', pipeNum ) ])

In [35]:
# Kim: this NN has input: 18 features, variables + onehotencoder
pipeNn5 = Pipeline([
    ('preprocessor', preprocessor ),
    ('model', MLPClassifier( hidden_layer_sizes=(5) ) )
], verbose=True)



#### Fit, predict, and assess

In [36]:
pipeNn5.fit( X_train, y_train )
predTrainNn5 = pipeNn5.predict( X_train )
predTestNn5 = pipeNn5.predict( X_test )

[Pipeline] ...... (step 1 of 2) Processing preprocessor, total=   0.1s
[Pipeline] ............. (step 2 of 2) Processing model, total=   4.5s


Pipeline(steps=[('preprocessor',
                 FeatureUnion(transformer_list=[('cat',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Card',
                                                                                                    'Marriage',
                                                                                                    'Pay_0'])])),
                                                                 ('encoder',
                                                                  OneHotEncoder(drop='first',
                                                                                dtype=<class 'int'>,
                                                                                sparse_output=False))])),
                                                ('num',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Limit_Bal',
                                                                                                    'Age',
                                                                                                    'Bill_Amt1',
                                                                                                    'Pay_Amt1'])])),
                                                                 ('scaler',
                                                                  StandardScaler())]))])),
                ('model', MLPClassifier(hidden_layer_sizes=5))],
         verbose=True)

In [37]:
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn5 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn5 )

0.6436041996365981

0.640690352255923

#### Checking the model weights

In [38]:
pipeNn5[ 'model' ].coefs_

[array([[ 4.56522642e-02,  5.62959165e-02,  2.49912614e-01,
          7.81129719e-02,  5.79058625e-02],
        [ 1.17666086e-01, -3.15519433e-01,  8.21387694e-03,
         -7.27293417e-02, -3.62408968e-01],
        [ 1.08069247e-01,  4.49572751e-02,  1.63601088e-01,
         -5.38488212e-02,  2.81225478e-01],
        [-3.98115901e-01, -5.10412782e-01,  9.83265126e-01,
          7.76611657e-01, -5.47206855e-01],
        [ 4.67122954e-01, -1.29156532e-01,  1.45766245e-01,
          2.88220833e-01, -3.09727129e-01],
        [-5.55844016e-01, -1.87055619e-01,  2.97361358e-02,
          6.71888578e-01, -9.39088939e-02],
        [ 6.20471607e-01,  1.23585254e-01, -2.93514054e-01,
          4.78431941e-03, -3.82998005e-02],
        [ 1.39736255e+00,  8.20147606e-02, -6.80591942e-01,
         -6.53153224e-01, -8.14669165e-01],
        [ 1.87229176e+00,  1.31169737e+00, -1.22798994e+00,
         -5.06243568e-01, -8.74891303e-01],
        [ 1.31767689e+00,  1.10473383e+00, -4.58810965e-01,
    

In [39]:
print(numpy.array_str(pipeNn5[ 'model' ].coefs_[ 0 ], precision=2, suppress_small=True))

[[ 0.05  0.06  0.25  0.08  0.06]
 [ 0.12 -0.32  0.01 -0.07 -0.36]
 [ 0.11  0.04  0.16 -0.05  0.28]
 [-0.4  -0.51  0.98  0.78 -0.55]
 [ 0.47 -0.13  0.15  0.29 -0.31]
 [-0.56 -0.19  0.03  0.67 -0.09]
 [ 0.62  0.12 -0.29  0.   -0.04]
 [ 1.4   0.08 -0.68 -0.65 -0.81]
 [ 1.87  1.31 -1.23 -0.51 -0.87]
 [ 1.32  1.1  -0.46 -0.43 -0.7 ]
 [-0.07  0.46  0.02 -0.68 -0.46]
 [ 0.04  0.   -0.24 -0.01 -0.04]
 [ 0.66  0.58 -0.41 -0.48 -0.19]
 [ 0.07  0.61  0.13 -0.46 -0.42]
 [ 0.25  0.94  0.55  0.1   0.35]
 [ 0.11  0.18 -0.07  0.22 -0.14]
 [ 0.3   0.1  -0.34 -0.1   0.41]
 [-0.95  0.2   0.07  0.23 -0.08]]


In [40]:
print( pipeNn5['preprocessor'].get_feature_names_out() )

['cat__selector__Card_Normal' 'cat__selector__Marriage_other'
 'cat__selector__Marriage_single' 'cat__selector__Marriage_unknown'
 'cat__selector__Pay_0_-1' 'cat__selector__Pay_0_0'
 'cat__selector__Pay_0_1' 'cat__selector__Pay_0_2'
 'cat__selector__Pay_0_3' 'cat__selector__Pay_0_4'
 'cat__selector__Pay_0_5' 'cat__selector__Pay_0_6'
 'cat__selector__Pay_0_7' 'cat__selector__Pay_0_8'
 'num__selector__Limit_Bal' 'num__selector__Age'
 'num__selector__Bill_Amt1' 'num__selector__Pay_Amt1']


### Deeper neural network, 3 layers

In [42]:
pipeNn555 = Pipeline([
    ('preprocessor', preprocessor),
    ('model',        MLPClassifier(hidden_layer_sizes=(5,5,5) ) )
], verbose=True)

#### Fit, predict, assess

In [43]:
pipeNn555.fit( X_train, y_train )
predTrainNn555 = pipeNn555.predict( X_train )
predTestNn555 = pipeNn555.predict( X_test )

[Pipeline] ...... (step 1 of 2) Processing preprocessor, total=   0.1s
[Pipeline] ............. (step 2 of 2) Processing model, total=   6.7s


Pipeline(steps=[('preprocessor',
                 FeatureUnion(transformer_list=[('cat',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Card',
                                                                                                    'Marriage',
                                                                                                    'Pay_0'])])),
                                                                 ('encoder',
                                                                  OneHotEncoder(drop='first',
                                                                                dtype=<class 'int'>,
                                                                                sparse_output=False))])),
                                                ('num',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Limit_Bal',
                                                                                                    'Age',
                                                                                                    'Bill_Amt1',
                                                                                                    'Pay_Amt1'])])),
                                                                 ('scaler',
                                                                  StandardScaler())]))])),
                ('model', MLPClassifier(hidden_layer_sizes=(5, 5, 5)))],
         verbose=True)

In [44]:
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn5 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn555 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn5 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn555 )

0.6436041996365981

0.6438020192251334

0.640690352255923

0.6420246454762811

### Wider neural network

In [45]:
pipeNnC = Pipeline([
    ('preprocessor', preprocessor),
    ('model', MLPClassifier(hidden_layer_sizes=(100) ) )
], verbose=True)
pipeNnC.fit( X_train, y_train )
predTrainNnC = pipeNnC.predict( X_train )
predTestNnC = pipeNnC.predict( X_test )

[Pipeline] ...... (step 1 of 2) Processing preprocessor, total=   0.1s


C:\Users\Mika Montonen\miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[Pipeline] ............. (step 2 of 2) Processing model, total=  27.7s


Pipeline(steps=[('preprocessor',
                 FeatureUnion(transformer_list=[('cat',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Card',
                                                                                                    'Marriage',
                                                                                                    'Pay_0'])])),
                                                                 ('encoder',
                                                                  OneHotEncoder(drop='first',
                                                                                dtype=<class 'int'>,
                                                                                sparse_output=False))])),
                                                ('num',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Limit_Bal',
                                                                                                    'Age',
                                                                                                    'Bill_Amt1',
                                                                                                    'Pay_Amt1'])])),
                                                                 ('scaler',
                                                                  StandardScaler())]))])),
                ('model', MLPClassifier(hidden_layer_sizes=100))],
         verbose=True)

In [46]:
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn5 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn555 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNnC )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn5 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn555 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNnC )

0.6436041996365981

0.6438020192251334

0.6641038650528496

0.640690352255923

0.6420246454762811

0.6471719454171049

### Wider and deeper

In [47]:
pipeNnCCC = Pipeline([
    ('preprocessor', preprocessor),
    ('model', MLPClassifier(hidden_layer_sizes=(100,100,100) ) )
], verbose=True)
pipeNnCCC.fit( X_train, y_train )
predTrainNnCCC = pipeNnCCC.predict( X_train )
predTestNnCCC = pipeNnCCC.predict( X_test )

[Pipeline] ...... (step 1 of 2) Processing preprocessor, total=   0.1s


C:\Users\Mika Montonen\miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[Pipeline] ............. (step 2 of 2) Processing model, total= 1.4min


Pipeline(steps=[('preprocessor',
                 FeatureUnion(transformer_list=[('cat',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Card',
                                                                                                    'Marriage',
                                                                                                    'Pay_0'])])),
                                                                 ('encoder',
                                                                  OneHotEncoder(drop='first',
                                                                                dtype=<class 'int'>,
                                                                                sparse_output=False))])),
                                                ('num',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnTransformer(transformers=[('selector',
                                                                                                   'passthrough',
                                                                                                   ['Limit_Bal',
                                                                                                    'Age',
                                                                                                    'Bill_Amt1',
                                                                                                    'Pay_Amt1'])])),
                                                                 ('scaler',
                                                                  StandardScaler())]))])),
                ('model', MLPClassifier(hidden_layer_sizes=(100, 100, 100)))],
         verbose=True)

In [ ]:
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn5 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn555 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNnC )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNnCCC )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn5 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn555 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNnC )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNnCCC )

### Tuning neural networks

In [49]:
pipeNn = Pipeline([
    ('preprocessor', preprocessor),
    ('model', MLPClassifier( max_iter=5000 ) )
], verbose=True)

paramGridNn = {
    'model__hidden_layer_sizes': [ (5), (10), (100), (10,10), (10,10,10), (50,50,50) ],
        'model__activation': ['identity', 'logistic', 'tanh', 'relu']
}

>>> gridNn = GridSearchCV( pipeNn, paramGridNn, cv=5, n_jobs=-1 )
>>> gridNn.fit( X_train, y_train )

[Pipeline] ...... (step 1 of 2) Processing preprocessor, total=   0.1s
[Pipeline] ............. (step 2 of 2) Processing model, total=   3.7s


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        FeatureUnion(transformer_list=[('cat',
                                                                        Pipeline(steps=[('selector',
                                                                                         ColumnTransformer(transformers=[('selector',
                                                                                                                          'passthrough',
                                                                                                                          ['Card',
                                                                                                                           'Marriage',
                                                                                                                           'Pay_0'])])),
                                                                                        ('encoder',
                                                                                         OneHotEncoder(drop='first',
                                                                                                       dtype=<class 'int'>,
                                                                                                       sparse_output=False))])),
                                                                       ('num',
                                                                        Pipeline(steps=[('selector',
                                                                                         ColumnTransformer(transformers=[('selector',
                                                                                                                          'passthrough',
                                                                                                                          ['Limit_Bal',
                                                                                                                           'Age',
                                                                                                                           'Bill_Amt1',
                                                                                                                           'Pay_Amt1'])])),
                                                                                        ('scaler',
                                                                                         StandardScaler())]))])),
                                       ('model', MLPClassifier(max_iter=5000))],
                                verbose=True),
             n_jobs=-1,
             param_grid={'model__activation': ['identity', 'logistic', 'tanh',
                                               'relu'],
                         'model__hidden_layer_sizes': [5, 10, 100, (10, 10),
                                                       (10, 10, 10),
                                                       (50, 50, 50)]})

In [50]:
gridNn.best_params_
gridNn.best_score_

{'model__activation': 'identity', 'model__hidden_layer_sizes': (10, 10, 10)}

0.8162

# Deeper Explanations

### ValueError Solutions

Googling and StackOverflow recommend setting the `handle_unknown` to 'ignore'.

You can also set `handle_unknown` to 'use_encoded_value' and set the `unknown_value` to something like -1.

In [ ]:
pipeLogistic = Pipeline([
    ('selector', ColumnTransformer([ ('selector', 'passthrough', lstCat ) ] )),
    ('encoder', OneHotEncoder( dtype=int, drop='first', sparse_output=False, handle_unknown='ignore') ),
    ('model', LogisticRegression() )
])
pipeLogistic.fit( X_train, y_train )
predTrainLogistic = pipeLogistic.predict( X_train )
sklearn.metrics.cohen_kappa_score( y_train, predTrainLogistic )

### Model attributes with trailing underscores

### Tuning alternatives

In [ ]:
gridNnBalanced = GridSearchCV( )
gridNnBalanced.fit( X_train, y_train )

In [ ]:
gridNnBalanced.best_params_
gridNnBalanced.best_score_

In [ ]:
predTrainNnBalanced =gridNnBalanced.best_estimator_.predict( X_train ) 
predTestNnBalanced = gridNnBalanced.best_estimator_.predict( X_test )

In [ ]:
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn5 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNn555 )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNnC )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNnCCC )
sklearn.metrics.balanced_accuracy_score( y_train, predTrainNnBalanced )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn5 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNn555 )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNnC )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNnCCC )
sklearn.metrics.balanced_accuracy_score( y_test, predTestNnBalanced )

### Inspecting and debugging pipelines

## Exercise: CustomerChurn.csv data.

Goal is to predict `churn`.

In [3]:
df = pandas.read_csv('~/Dropbox/BZAN3307/CustomerChurn.csv')
numpy.random.seed(28)
X_train, X_test, y_train, y_test = train_test_split(df, df.Churn, test_size=0.5)